### PR TITLE
Creating an `off_focus` hook in `TextBox2D`

### PR DESCRIPTION
**Pull request by ganimtron-10**
To know when the user has completed editing in the `TextBox2D`, creating an `on_blur` hook.
Required in #499 .
Also changing the condition sequence in the `handle_character` function,  because when we press "return" key instead of removing focus from the UI it adds the "\r" character to the message.

### CODE REVIEW

**Comment by Garyfallidis** [comment]
Please use ``focus_in`` or ``focus_out`` instead of ``on_blur``. Alternatively, ``off_focus/on_focus``.

**Comment by Garyfallidis** [comment]
A test is missing too.

**Comment by ganimtron-10** [comment]
Hey @skoudoro ,
I have updated the hook name and also added the tests for the same.
PTAL.
Thanks!

**Review by skoudoro — APPROVED** [review]
Thank you for this PR @ganimtron-10. 

Looks good to me. merging

**Pull request merged**
