### PR TITLE
[DOC] fix warnings

### PR DESCRIPTION
**Pull request by robinroy03**
fix for #936 - WIP

### CODE REVIEW

**Review by skoudoro — APPROVED** [review]
Thank you @robinroy03! merging

**Comment by skoudoro** [comment]
ah ok, it is a draft, waiting for the final version

**Comment by robinroy03** [comment]
@skoudoro im having more py files coming

**Comment by robinroy03** [comment]
@skoudoro check now.

Some tutorial .py files got numpy migration errors. I've not upgraded them here. The code here is just keyword error flags.
I'll open a new issue about the numpy migration errors.

**Comment by skoudoro** [comment]
Thank you for this @robinroy03, it looks good, merging

**Pull request merged**
