### PR TITLE
The grid - add actors in a grid and interact with each one of them independently

### PR DESCRIPTION
**Pull request by Garyfallidis**
image

@bramshq, @MarcCote and all have a look. 

In summary, I refactored Marco's PR #25. Renamed InteractorStyleBundlesGrid to InteractorStyleGrid and added a test called test_grid.

### CODE REVIEW

**Comment by Garyfallidis** [comment]
Will correct these PEP8s asap. Hopefully by tomorrow night.

**Comment by MarcCote** [comment]
Should we try to have UI components as well in your test? I'm guessing it will fail because we use the wrong interactor style.

I think there's probably a way of using our custom interactor style (the one uset with the UI components).

**Comment by MarcCote** [comment]
Héhé 
image

**Comment by MarcCote** [comment]
Even better with https://github.com/Garyfallidis/fury/pull/1
image

**Comment by skoudoro** [comment]
@pep8speaks Resume now.

**Comment by PDN96** [comment]
@Garyfallidis I was just exploring some examples in vtk and came accross this:
https://vtk.org/Wiki/VTK/Examples/Python/Visualization/AssignColorsCellFromLUT

I ran the code and it looked like a 2D version of this. Maybe it can give you some ideas!

capture

**Comment by skoudoro** [comment]
I am merging that for now, I will improve test and code quality on another PR. Thank you @Garyfallidis  @MarcCote for the hard work and this very cool feature!

**Comment by MarcCote** [comment]
Awesome, thank you both.

**Pull request merged**
