### PR TITLE
Fixed Pycodestyle errors in fury/actors/odf_slicer.py, fury/actors/peak.py, fury/actors/tensor.py, and fury/data/fetcher.py

### PR DESCRIPTION
**Pull request by WassCodeur**
This Pull Request corrects errors in fury/actors/odf_slicer.py, fury/actors/peak.py, fury/actors/tensor.py and fury/data/fetcher.py.

fix:  #876

The following changes have been made:

    Files: fury/actors/odf_slicer.py, fury/actors/peak.py and fury/data/fetcher.py
        White spaces correction
        error correction: E501 line too long

    File fury/actors/tensor.py:
           error correction: W605 invalid escape sequence '\D'

Tests:

I've run some tests to make sure the changes haven't affected the way the code works.

Coding conventions:

I have followed PEP8 coding conventions in this Pull Request.

Acknowledgements:

I thank the project contributors for their work and time.

I hope this Pull Request will be useful and that it will be integrated into the project.

Please don't hesitate to ask me questions if you need further information.

I'm still doing my best to fix the other pycodestyle errors in the other files.

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @WassCodeur,

Thank you for doing this!

See above, there is still an issue: https://github.com/fury-gl/fury/pull/877#issuecomment-2028194877

Please, can you fix it?

**Comment by WassCodeur** [comment]
Sure

**Comment by skoudoro** [comment]
Do you have an update on this ?

**Comment by WassCodeur** [comment]
yes I'm working on it, and I'll push it soon

**Comment by skoudoro** [comment]
LGTM, merging, Thanks @WassCodeur

**Comment by WassCodeur** [comment]
@skoudoro Always here to contribute! 🙌

**Pull request merged**
