### PR TITLE
NF: Add lazy_loader feature  in FURY

### PR DESCRIPTION
**Pull request by WassCodeur**
This pull request introduces the ``lazy_loader`` feature to optimize module loading in the ``FURY`` . Lazy loading improves performance by deferring the loading of modules until they are actually needed, thus reducing startup times and memory footprint.

**Changes included in this PR:**

-   Implementation of lazy loading across multiple modules in ``FURY``.
-  Updated ``__init__.py`` files to support lazy loading where necessary.
-  Added type stubs (``__init__.pyi``) to provide type indications for lazy loading modules.
-  Improved module organization and structure to effectively support lazy loading.

This feature aims to improve the user experience by speeding up application start-up and improving overall performance in scenarios where not all modules are immediately required.

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you for this. Can you rebase ?

**Comment by deka27** [comment]
Hi @WassCodeur , why does this have the keyword decorator commit?
Also, I believe you should have a look at the lazy loading implementation in [Scikit-Image](https://github.com/scikit-image/scikit-image/tree/20ca1f2638778f9e6cbf2361b9fa106af1a40e98/skimage).
You will have to make changes in [pyproject.toml](https://github.com/fury-gl/fury/blob/master/pyproject.toml)

https://github.com/fury-gl/fury/blob/43540d3534e907241c84969915d38a072d2ee66c/pyproject.toml#L44C1-L52C2

**Comment by WassCodeur** [comment]
Hi @deka27!
Thank you. By the way, I had created the lazy_loader branch from the keyword_only branch. Thanks a lot for the reminder to update the ``pyproject.toml``.

**Comment by deka27** [comment]
Okay, I understand. I feel you could have implemented as a new feature branch only. Also u might need `py.typed` file.

**Comment by WassCodeur** [comment]
Okay, thanks  a lot @deka27 . I'll look into integrating `py.typed`.

**Review by skoudoro — APPROVED** [review]
Hi @WassCodeur,

Thank you for this! I tried and it works like a charm. I compared performance using `python -X importtime -c "import fury; import fury.lib" 2>import.log` and I see improvement so it is ready to go. 

merging

**Pull request merged**
