### PR TITLE
Added Horizontal Layout to `layout` module

### PR DESCRIPTION
**Pull request by antrikshmisri**
This PR adds support for `HorizontalLayout` in `layout` module. Below is a screenshot for reference.

Screenshot (4)

### CODE REVIEW

**Review by skoudoro — APPROVED** [review]
Hi @antrikshmisri ,

LGTM, I need to try it with a UI element but overall, it seems good. 

@Nibba2018, can you look at this also? Thanks!

**Comment by antrikshmisri** [comment]
> LGTM, I need to try it with a UI element but overall, it seems good. 

Hey @skoudoro , this won't work with UI elements until #443 is merged.

**Comment by skoudoro** [comment]
> Hey @skoudoro , this won't work with UI elements until #443 is merged.

Right, so we are just waiting for @Nibba2018 review

**Comment by skoudoro** [comment]
I am going ahead and merge this PR. thanks @antrikshmisri

**Pull request merged**
