### PR TITLE
Adding Week2 BlogPost

### PR DESCRIPTION
**Pull request by ganimtron-10**
image

### CODE REVIEW

**Review by JoaoDell — APPROVED** [review]
Hey @ganimtron-10, just sucessfully built your blogpost and read it all. Nice short description, everything is fine 👍

**Review by tvcastillod — COMMENTED** [review]
@ganimtron-10 Nice blogpost. Everything looks good.

**Comment by ganimtron-10** [comment]
Thanks @JoaoDell & @tvcastillod for the review.

**Review by skoudoro — APPROVED** [review]
Nice blog posts. Looks good to me.

Merging. thanks @ganimtron-10!

**Pull request merged**
