### PR TITLE
Changed options attribute from list to dict and updated respective tests

### PR DESCRIPTION
**Pull request by devmodi154**
This is the new PR, a fix for issue #76 as per discussion.

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you for the update! I will get back to you as soon as I test it

**Comment by skoudoro** [comment]
supersede and close #152

**Comment by devmodi154** [comment]
@skoudoro I think I can add `get_option` function as mentioned issue before merging this if could help me with a doubt about it

**Comment by skoudoro** [comment]
Sorry, I merged before answering your question.  

I do not think we need a `get_option`, it will be more confusing. The class has already a public attribute `option`.  the get/set method would be useful if our attribute was private/protected (meaning `_option` or  `__option`).

**Comment by skoudoro** [comment]
So, it was a mistake from me on the issue. I had another idea initially but this solution is ok.
thank you @devmodi154

**Pull request merged**
