### PR TITLE
added primitive and actor for triangular prism, added tests too

### PR DESCRIPTION
**Pull request by SunTzunami**
I made a primitive for triangular prism and created an actor for the same. Added tests for actor and primitive too. 
Preview -

prism

### CODE REVIEW

**Review by skoudoro — COMMENTED** [review]
Hi @SunTzunami,

It looks good! Thank you!  I just need to check if your unit prism is centered.

**Review by skoudoro — COMMENTED** [review]
Hi @SunTzunami,

You will have to update your primitive. Indeed, the default position of your primitive is **NOT centered** and **NOT well oriented**. See below the basic script and the resulting problem:

```python
import numpy as np
from fury import actor, window

scene = window.Scene()
g_actor = actor.octagonalprism(centers=np.array([[0, 0, 0]]))  # actor.triangularprism(centers=np.array([[0, 0, 0]]))
scene.add(g_actor, actor.axes())
window.show(scene
```

| Octogonal Prism | trianguler prism |
|---------------|--------------------|
| Capture d’écran 2021-03-25 à 00 27 56  |  Capture d’écran 2021-03-25 à 00 27 24   |  

Let me know if you have any questions

**Comment by SunTzunami** [comment]
Thanks or the review @skoudoro ! I updated the primitive- 
| Octagonal Prism | Triangular Prism |
| ------------- | ------------- |
|octa|tri|

I updated the test accordingly.. 
PTAL. Thank you!

**Review by skoudoro — COMMENTED** [review]
Hi @SunTzunami,

Thank you for the update. It would be better if you flip the Y axes (in green).

Currently, you triangular point down instead of up.

Thank you

**Comment by SunTzunami** [comment]
Hi @skoudoro ! I updated the primitive and the tests so that the prism points upwards - 

tri

**Review by skoudoro — APPROVED** [review]
Thank you for the update. merging

**Pull request merged**
