### PR TITLE
glTF skinning animation implementation

### PR DESCRIPTION
**Pull request by xtanion**
latest update: `viz_skinning_hirearchical_transform.py`

### CODE REVIEW

**Comment by skoudoro** [comment]
Can you resolve all the conflict and update this PR before our meeting @xtanion? 

Thank you

**Comment by skoudoro** [comment]
Also, please, add the test for interpolator.py in this PR

**Comment by xtanion** [comment]
I modified the docs @skoudoro, it's ready for review now.

**Comment by skoudoro** [comment]
Thank you for this work @xtanion, LGTM

**Pull request merged**
