### PR TITLE
Overload set_visibility for Panel2D and Combobox2D

### LINKED ISSUE #731: Clicking the tab of a ComboBox2D opens dropdown without changing icon
## Description
Basically, when in the below code, I click on the colors title bar while my drop down is closed, it opens the menu without changing the icon. This leads to the icons getting flipped (i.e. closed icon corresponding to an open menu, and vice versa)

## Way to reproduce
```py 
from fury import ui, window, actor
import numpy as np
from fury.data import fetch_viz_icons


fetch_viz_icons()

colors = {
    "Violet": (0.6, 0, 0.8),
    "Indigo": (0.3, 0, 0.5),
    "Blue": (0, 0, 1),
    "Green": (0, 1, 0),
    "Yellow": (1, 1, 0),
    "Orange": (1, 0.5, 0),
    "Red": (1, 0, 0)
}

tab_ui = ui.TabUI(position=(49, 94), size=(300, 300), nb_tabs=1 , draggable=True)
color_combobox = ui.ComboBox2D(items=list(colors.keys()),
                               placeholder="Choose Text Color",
                               size=(250, 150), draggable=True)

tab_ui.add_element(0, color_combobox, (0.1, 0.3))
label = ui.TextBlock2D(
    position=(600, 300), font_size=40, color=(1, 0.5, 0),
    justification="center", vertical_justification="top",
    text="FURY rocks!!!")                               

def change_color(combobox):
    label.color = colors[combobox.selected_text]

tab_ui.tabs[0].title = "Colors"
color_combobox.on_change = change_color
sm = window.ShowManager(size=(800, 500), title="Viz Tab")
sm.scene.add(tab_ui,label)
interactive = True

if interactive:
    sm.start()
```
image

{'fury_version': '0.8.0.post1454+g3771685a', 'pkg_path': '/home/percy/fury/fury', 'commit_hash': '3771685aa1f84f71ef9568b4731295dfaf707de4', 'sys_version': '3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]', 'sys_executable': '/usr/bin/python3', 'sys_platform': 'linux', 'numpy_version': '1.24.1', 'scipy_version': '1.10.0', 'vtk_version': '9.2.5', 'matplotlib_version': '3.6.3'}

### PR DESCRIPTION
**Pull request by dwijrajhari**
**Related issue:** #731 (Clicking the tab of a ComboBox2D opens dropdown without changing icon)

Currently, the way set_visibility is implemented, it collects a list of all the actors down the tree and sets visibility of all of them. Thus the child elements of, say a Panel2D, don't get to choose which actors of themselves they want to make visible.
Thus when a TabPanel2D containing a comboBox2D is selected, it sets the visibility of the comboBox's drop_down_menu to true, even though its _menu_visibility is set to false. 

**Possible fix:** We overload the set_visibility method of Panel2D to call set_visibility on all of its elements. We then overload the set_visibility of comboBox2D to only make the dropdown visible if _menu_visibility is true

This change fixes #731 and also passes existing tests in `fury\ui\tests`

However, since I am not fully aware of the codebase, I don't know if there was a particular reason, set_visiblility was implemented that way. @skoudoro Could you give me some hints?

### CODE REVIEW

**Comment by dwijrajhari** [comment]
@skoudoro Added test. Kindly review

**Comment by ganimtron-10** [comment]
@dwijrajhari can you rebase this PR so that we can review it?

@skoudoro 
This looks a good solution for the issue #562 #731

**Comment by ganimtron-10** [comment]
@skoudoro Please have a look at this PR!

**Comment by skoudoro** [comment]
Hi @ganimtron-10 and @dwijrajhari,

I think the fix can be even simpler than that. Actually, I do not succeed to reproduce the issue on the main branch. 

I agree that the arrow do not start on the right position but after 2 clicks, all is good. it look like an initialization issue and not `set_visibility` issue. I am not 100% sure. 

So I recommend to test https://github.com/fury-gl/fury/issues/731 using master branch.

**Comment by skoudoro** [comment]
Ok, I looked deeper, I see what you are doing.

**Pull request merged**
