### PR TITLE
GSoC: Week 10 Blogpost

### PR DESCRIPTION
**Pull request by JoaoDell**
Hello everyone, here is my week 10 blogpost:
image

### CODE REVIEW

**Review by ganimtron-10 — COMMENTED** [review]
Hey @JoaoDell,
Nice Blog! LGTM.
Also let me know if you are still facing those issues with the UI will try to look at it as well.

**Review by tvcastillod — COMMENTED** [review]
Hi @JoaoDell 
The blogpost is generating correctly, it looks good to me.

**Comment by JoaoDell** [comment]
Thanks for the review @ganimtron-10 and @tvcastillod :)

**Comment by JoaoDell** [comment]
> Hey @JoaoDell, Nice Blog! LGTM. Also let me know if you are still facing those issues with the UI will try to look at it as well.

Sure, I need to look further into it to understand what is happening, but as I am on windows, I could not debug it properly to understand if it is a problem with the API or the UI itself. I may ping you later if I can take a look on that

**Review by skoudoro — APPROVED** [review]
All good, thanks @JoaoDell, merging

**Pull request merged**
