### PR TITLE
Modified Arrow actor to use repeat primitive by default

### PR DESCRIPTION
**Pull request by m-agour**
### Test code
```
import numpy as np  
from fury import window, actor  
  
scene = window.Scene()  
  
center_rs = np.array([[0, 0, 0]])  
center_rp = np.array([[0, 1, 0]])  
direction = np.array([[0, 0, 0]])  
color_rs = np.array([[1, 0, 0]])  
color_rp = np.array([[0, 1, 0]])  
  
rpactor = actor.arrow(center_rp, direction, colors=color_rp, scales=1)  
rsactor = actor.arrow(center_rs, direction, colors=color_rs, repeat_primitive=False)  
  
scene.add(rpactor)  
scene.add(rsactor)  
  
window.show(scene, size=(600, 600), reset_camera=False, title='Comparing')
```
image

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @m-agour,

Thank you for this! This is a busy month, I will review your PR ASAP. Maybe @guaje, @Garyfallidis, or other maintainers will be available to review your PR earlier.

During this time, can you make sure to add/fix:

- pep8
- Unit test (check the other primitives tests)
- update or add a tutorial
- check orientation
- add on this PR different screenshots.

Thanks

**Comment by m-agour** [comment]
Hello @skoudoro,
Taking your advice, I've checked the orientation of the arrow actor and found two problems:
1. By setting the direction of the repeate_source based arrow to (0, 0, 0), I found that the original direction of the arrow is (1, 0, 0). 
2. The second problem is that the rotation of the repeat_sources is not the same as the repeat_primitive rotation for the same arrow object. I will write about it in more detail in a separate issue.

**Comment by m-agour** [comment]
Hello @skoudoro .
I've made some progress. would you take a look at it and let me know if anything is missing?

**Comment by m-agour** [comment]
Hello @skoudoro .
I've made some progress. Would you take a look at it and let me know if anything is missing?

**Pull request merged**
