### PR TITLE
Remove alias keyword on documentation

### PR DESCRIPTION
**Pull request by skoudoro**
This PR improves API generation by providing a more fine-grained control over the functions/classes to document which removes a lot of `alias` keyword
We document also the `lib` module to avoid the `alias` keyword

### CODE REVIEW

**Comment by Garyfallidis** [comment]
Cannot wait to merge this! @skoudoro ! Is this ready?

**Comment by skoudoro** [comment]
I am doing a last check locally and it is ready to merge

**Comment by skoudoro** [comment]
ok, you can go ahead and merge it @Garyfallidis

**Comment by Garyfallidis** [comment]
💯

**Pull request merged**
