### PR TITLE
Added Dark mode, Fixed Search Bar for documentation site

### PR DESCRIPTION
**Pull request by deka27**
# Introduction of Dark Mode & Search Bar Fix

## Description
- This pull request introduces two main enhancements to the project. Firstly, it implements a Dark mode feature, allowing users to switch between light and dark themes for improved readability and reduced eye strain in low-light environments. Secondly, it addresses an issue with the search bar functionality, the search icon being non-functional and the shortcut accessibility also being non-functional. These changes aim to enhance the user experience by providing a more versatile interface and ensuring smoother navigation and interaction within the application.

## Related Issues
- No Related Issues

## Changes Made
* Updated Python-sphinx-theme from 0.12.0 to 0.15.2(Stable)
* Implemented Dark mode feature.
* Fixed issues related to the search bar functionality. (Search Icon in Navbar, and shortcut not functional)
* Added toggle functionality for Dark mode in the UI.
* Adjusted CSS styles to accommodate Dark mode.
* Conducted testing to validate the behavior of both Dark mode and the search bar.
* Added comments wherever necessary to explain the code modification

## Screenshots

Light Mode
image

Dark Mode
image

## Checklist
- [x] I have reviewed my own code changes.
- [x] I have tested my changes locally.
- [x] My code follows the project's coding standards.
- [x] I have updated relevant documentation or comments.

## Additional Notes
* I haven’t added any new dependency, I have just updated the pydata-theme. There are somethings that were deprecated and I have fixed them (whatever I found). In my tests I didn’t see anymore conflicts. 
* Depending on how you want the looks to be, further styling improvements might be required.
* I didn’t specifically find any open issues related to my changes.
* I wasn’t quite sure about the tests related to documentation changes specifically. I did the ones mentioned in the contribution section.

### CODE REVIEW

**Comment by deka27** [comment]
@skoudoro I noticed a small mistake with my last PR. Created this new one for the fix.

**Review by skoudoro — APPROVED** [review]
Thank you @deka27,

Looks good to me. merging. 

ps: there is a small issue, you need to click twice on dark/light button to see the change, which is strange. But for now, it is ok

**Comment by deka27** [comment]
> Thank you @deka27,
> 
> Looks good to me. merging.
> 
> ps: there is a small issue, you need to click twice on dark/light button to see the change, which is strange. But for now, it is ok

So, actually, you have to click twice because there are 3 modes,
- Light
- Dark
- System

System mode is if you want the site to automatically load according to the OS settings, it comes from the theme itself.

**Comment by skoudoro** [comment]
> System mode is if you want the site to automatically load according to the OS settings, it comes from the theme itself.

Good to know! thanks !

**Pull request merged**
