### PR TITLE
Adding morphing support in `gltf.py`

### PR DESCRIPTION
**Pull request by xtanion**
**NOTE: Skinning PR (#685) needs to be merged before merging this**

Preview:
Using the `MorphStressTest` model and `TheWave` animation.

https://user-images.githubusercontent.com/74976752/193900336-8bd84ed5-af4e-4349-9c23-9c4557b09484.mp4

### CODE REVIEW

**Review by skoudoro — COMMENTED** [review]
Hi @xtanion,

it is hard to see the difference. Can you rebase this PR? 

Thank you!

**Comment by m-agour** [comment]
Hello @skoudoro @xtanion, when is this PR getting merged?

**Comment by skoudoro** [comment]
Tahnk you @xtanion, Look goods and works great

**Comment by m-agour** [comment]
@skoudoro Thanks you. I will do that.

**Pull request merged**
