### PR TITLE
Surface actor colormap fix

### PR DESCRIPTION
**Pull request by amitchaudhari9121**
Hi! 
This is a fix for issue #429 .
@SunTzunami and I hopped on a call and fixed it together.

### Now

Screenshot 2021-05-01 at 6 42 31 PM

I think, this is exactly how It should look...
I've also changed the documentation to include the range of the Individual color values. 
In case someone else is confused due to this.

### CODE REVIEW

**Comment by SunTzunami** [comment]
@amitchaudhari9121 Thanks for the PR. 
And yes that's how it's supposed to look!!

**Review by skoudoro — COMMENTED** [review]
Hi @amitchaudhari9121,

Thank you for this fix. As usual, it needs tests to avoid reproducing this issue.

Furthermore, we need to check what is the rules.  Are the other actors expecting 0-1 or 0-255. we should make sure that is uniform everywhere.

**Comment by amitchaudhari9121** [comment]
>Furthermore, we need to check what is the rules. Are the other actors expecting 0-1 or 0-255. we should make sure that is uniform everywhere.

I've skimmed `actor.py` through all mentions of color, and yes. 
It is the norm in all of actor.py.

>As usual, it needs tests to avoid reproducing this issue.

I'm not sure on how do i go about testing it.
I'd like suggestions about this.

Do we need to test it? 
Like nothing stops working if you don't give it a proper input. ( I tried giving it 255, thinking it would crash, but it just rendered with a wrong colormap )
Even If I go above the limit of 1, It seems to work fine, Just not display color properly.

**Comment by SunTzunami** [comment]
I think you could raise an error when the user inputs a color that's out of bounds. @skoudoro  will be able to guide better.

**Comment by skoudoro** [comment]
We might let pass this PR and create a specific PR for all actors to raise an error if a color is out of bounds. Still thinking about it 🤔 ...

**Comment by amitchaudhari9121** [comment]
Ok 👌
Thank you!

**Comment by guaje** [comment]
@amitchaudhari9121, @skoudoro, and @SunTzunami.

This is blocking #362. Is any of you working on the "check out of bounds" PR or what are the steps to merge/close this and #362?

**Comment by SunTzunami** [comment]
@guaje once this is done, #362 will work as intended and I'll update it to be merged. 
As for the out of bounds, I did a quick scan of [actor.py](https://github.com/fury-gl/fury/blob/master/fury/actor.py). The following functions seem to take input range from 0 to 255 -
1. [slicer](https://github.com/fury-gl/fury/blob/master/fury/actor.py#L31)
2. [odf_slicer](https://github.com/fury-gl/fury/blob/master/fury/actor.py#L852)

Unsure about - 

3. [tensor_slicer](https://github.com/fury-gl/fury/blob/master/fury/actor.py#L915) as the range of acceptable colors is not clearly mentioned but the docstring mentions [RGB input](https://github.com/fury-gl/fury/blob/master/fury/actor.py#L938).
4.  [_tensor_slicer_mapper](https://github.com/fury-gl/fury/blob/master/fury/actor.py#L1000) as the range of acceptable colors is not clearly mentioned but the docstring mentions [RGB input](https://github.com/fury-gl/fury/blob/master/fury/actor.py#L1021).

@skoudoro and @amitchaudhari9121

**Comment by amitchaudhari9121** [comment]
@guaje I can't find the time to work for fury for the moment, I'm busy with my intern at Linux foundation, 
Could you please explain how this is blocking #362 ?

As far as i remember (its been weeks since those commits), going out of bounds just messes up the colormap displayed. 
which is hard to notice at times. 

Personally, I don't think we need to add tests for it, it's mentioned clearly in the doc for that function, and any wrong input does not crash anything. We could merge this as is, and not have any problems.

@skoudoro  @SunTzunami  your thoughts?

**Comment by SunTzunami** [comment]
@amitchaudhari9121 for #362 to work optimally, colormap need to work with surface actor (which was not the case before this PR). Once this PR is merged, colormaps will work with surface actor and #362 will work.

**Comment by skoudoro** [comment]
Hi All, 

This PR can be merged so I will go ahead. However, we need to clarify the rules concerning the color ([0-1], vs [0-255]).

Let's create an issue to remember that we need to handle the color in all actors. I suppose, there is a function for that in utils.py or we need to create it.

**Comment by skoudoro** [comment]
Thanks @amitchaudhari9121 for this. Merging!

**Pull request merged**
