### PR TITLE
Added week 5 blog post

### PR DESCRIPTION
**Pull request by m-agour**
image

### CODE REVIEW

**Review by ganimtron-10 — COMMENTED** [review]
Hello @m-agour ,
Nice Blog! LGTM.
Thanks!

**Review by xtanion — COMMENTED** [review]
Perfect blog @m-agour, No typos or grammatical errors. Good Job!

**Comment by m-agour** [comment]
Thanks, @ganimtron-10, @xtanion for your review.

**Review by skoudoro — APPROVED** [review]
LGTM! merging

**Pull request merged**
