### PR TITLE
Added Dark mode, Fixed Search Bar for documentation site

### PR DESCRIPTION
**Pull request by deka27**
# Introduction of Dark Mode & Search Bar Fix

## Description
- This pull request introduces two main enhancements to the project. Firstly, it implements a Dark mode feature, allowing users to switch between light and dark themes for improved readability and reduced eye strain in low-light environments. Secondly, it addresses an issue with the search bar functionality, the search icon being non-functional and the shortcut accessibility also being non-functional. These changes aim to enhance the user experience by providing a more versatile interface and ensuring smoother navigation and interaction within the application.

## Changes Made
* Updated Python-sphinx-theme from 0.12.0 to 0.15.2(Stable)
* Implemented Dark mode feature.
* Fixed issues related to the search bar functionality.
* Added toggle functionality for Dark mode in the UI.
* Adjusted CSS styles to accommodate Dark mode.
* Conducted testing to validate the behavior of both Dark mode and the search bar.
* Added comments wherever necessary to explain the code modification

## Screenshots

Light Mode
image

Dark Mode
image

## Checklist
- [x] I have reviewed my own code changes.
- [x] I have tested my changes locally.
- [x] My code follows the project's coding standards.
- [x] I have updated relevant documentation or comments.

## Additional Notes
* I haven’t added any new dependency, I have just updated the pydata-theme. There are somethings that were deprecated and I have fixed them (whatever I found). In my tests I didn’t see anymore conflicts. 
* Depending on how you want the looks to be, further styling improvements might be required.
* I didn’t specifically find any open issues related to my changes.
* I wasn’t quite sure about the tests related to documentation changes specifically. I did the ones mentioned in the contribution section.

### CODE REVIEW

**Comment by skoudoro** [comment]
Thank you for doing this @deka27, I will check all of that tonight and give you some feedback

**Comment by deka27** [comment]
I found 1 issue with my PR, i am closing this one, I will put a new request soon.

**Comment by skoudoro** [comment]
Hi @deka27,

You do not need a new pull request, you can fix the issue on this pull request

**Comment by deka27** [comment]
@skoudoro It was something related to my merge issue. So I just wanted to do it with a clean slate.

**Pull request closed without merging**
