### PR TITLE
Utils vtk

### PR DESCRIPTION
**Pull request by ibrahimAnis**
I have added utility functions in utils.py file and add test files in tests folder. Tests for compute_bounds() and update_actor() functions are created which was not made properly in my previous pull request. In reference to issue #179 please review my pull request and give feedback to me.

### CODE REVIEW

**Comment by Nibba2018** [comment]
You can check for PEP8 issues by running `flake8 path/to/filename.py` instead of pushing multiple commits.

**Comment by ibrahimAnis** [comment]
> You can check for PEP8 issues by running `flake8 path/to/filename.py` instead of pushing multiple commits.

Thanks bro. I did not know that

**Comment by ibrahimAnis** [comment]
I have added new utility function get_bounds() which will return the bounds of actor and I have also made new test functions to check compute_bounds() and update_actor(). I hope you will like it @skoudoro . Please review it and give me feedback.

**Comment by skoudoro** [comment]
Thank you @ibrahimAnis! merging

**Comment by ibrahimAnis** [comment]
Thanks @skoudoro .

**Pull request merged**
