### PR TITLE
Flocking-simulation using boid rules

### PR DESCRIPTION
**Pull request by RajPaliwal10**
Hi please verify my code.

### CODE REVIEW

**Review by RajPaliwal10 — COMMENTED** [review]
just a trial

**Review by RajPaliwal10 — COMMENTED** [review]
trial

**Comment by SunTzunami** [comment]
Hi @RajPaliwal10 
Thanks for creating this PR. 
If you want to check pep8 locally, refer to [this](https://flake8.pycqa.org/en/latest/).

**Comment by RajPaliwal10** [comment]
hey, @SunTzunami thanks for your help man !!!

**Review by skoudoro — COMMENTED** [review]
Hi @RajPaliwal10,

Thank you for this. This PR needs a lot of work.

- Can you remove pygame and replace it with fury? 
- Can you fix all pep8 issues?
- Why are you deleting README.md?
- Can you remove all temporary files like `__pycache__` folder or `*.pyc`?
- I recommend you to use Numpy for matrix_multiplication, rotation, etc. Look also in FURY, we have multiple functions already implemented.
- Please, follow python syntax (snake_case)
- Can you document all your functions?
- Please, avoid using `import *`.

You can fix all these issues directly on this PR. No need to open a new one.

Thank you

**Comment by Garyfallidis** [comment]
@nasimanousheh have you seen this PR? We already have a PR for BOIDS so why this is more useful or important @RajPaliwal10?

**Comment by skoudoro** [comment]
Hi @RajPaliwal10,

@Garyfallidis is referring to this PR #330. Can you look into it and compare both solutions? 

Thank you

**Comment by RajPaliwal10** [comment]
Hi @skoudoro @Garyfallidis  Thanks for your replies!!
I am learning the fury library and If you find this project repetitive then I have one more project idea and I am working on it. I am going to implement it using fury.

**Comment by skoudoro** [comment]
Hi @RajPaliwal10, 

What is the status of this work? Did you have time to compare? Did you have time to clean this PR? 
Please, keep us updated, otherwise, we will have to close this PR.

Thanks !

**Comment by RajPaliwal10** [comment]
Sorry but I am dealing with my end semester examinations so I didn't get
the time to look at it. You can close this PR I will be back in some days.
Thank You!!!

**Pull request closed without merging**
