### PR TITLE
UI Bug fixes for Horizon

### PR DESCRIPTION
**Pull request by maharshi-gor**
This PR solves the issues for the UI bugs that appear for Horizon.

 #### Following is fixed in this PR
1. Solution for disks not appearing in the right position.
2. Combo Box being out of the bounds of the tabs and with a huge size down button.

#### Methodology Used
1. The _set_position (Initial position set method used by panel (TabUI)) method was setting the coordinates of the handles differently than the set_position method invoked when slider is moved. Making them consistent solved the issue.
2. Combo Box was calculating its location from end of the drop_down_menu instead of the selected text. While passing the  values in _set_position method. We just subtracted the y coordinate with the size of dropdown menu

#### Experiment results
**Intital opening**
Screenshot from 2024-02-20 09-57-34

**Opened Combo Box**
Screenshot from 2024-02-20 09-57-44

**Selected Combo Box**
Screenshot from 2024-02-20 09-57-55

#### Code to experiment

```
from fury import ui, window

# Create scene
scene = window.Scene()

# Create show manager
show_m = window.ShowManager(
    scene,
    size=(1200, 900),
    reset_camera=False
)

d_slider = ui.LineDoubleSlider2D(
    min_value=-100,
    max_value=100,
    line_width=3,
    length=450,
    outer_radius=8,
    font_size=16
)
slider = ui.LineSlider2D(
    min_value=-100,
    max_value=100,
    line_width=3,
    length=450,
    outer_radius=8,
    font_size=16
)

d_slider.default_color = (1., .5, .0)
d_slider.track.color = (.8, .3, .0)
d_slider.active_color = (.9, .4, .0)

slider.default_color = (1., .5, .0)
slider.track.color = (.8, .3, .0)
slider.active_color = (.9, .4, .0)

d_slider.handles[0].color = (1., .5, .0)
d_slider.handles[1].color = (1., .5, .0)

slider.handle.color = (1., .5, .0)


c_box = ui.ComboBox2D(
    items=['red', 'green', 'blue', 'pink', 'white', 'orange'],
    selection_bg_color=(0, 0, 0),
    selection_text_color=(0.7, 0.7, 0.7), draggable=False,
    position=(200, 200))

tab_ui = ui.TabUI(
        position=(5, 5), size=(1000, 240), nb_tabs=1,
        active_color=(1, 1, 1), inactive_color=(0.5, 0.5, 0.5),
        draggable=True)

tab_ui.add_element(0, d_slider, (.52, .35))
tab_ui.add_element(0, slider, (.52, .65))
tab_ui.add_element(0, c_box, (.52, .85))

scene.add(tab_ui)
# scene.add(d_slider)
# scene.add(c_box)

show_m.render()
show_m.start()
```

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @maharshi-gor,

Thank you for this, Can you also update the unittests? thanks !

**Comment by skoudoro** [comment]
There is still some tests failing. Can you rebase your PR. I fixed main so you will be able to see the issue

**Review by skoudoro — CHANGES_REQUESTED** [review]
Tests are still failing. To check more deeply

**Comment by Garyfallidis** [comment]
Thank you @maharshi-gor !

**Pull request merged**
