### PR TITLE
STYLE: Change examples `README` file extension to markdown

### PR DESCRIPTION
**Pull request by jhlegarreta**
Change examples `README` file extension to markdown.

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @jhlegarreta,

Did you check if sphinx-gallery is happy with this change? Did you try to generate the documentation? Thank you for your feedback

**Comment by jhlegarreta** [comment]
I have not @skoudoro . [The equivalent file in DIPY](https://github.com/dipy/dipy/blob/master/doc/examples/README.md) is also a Markdown file, and in the [Sphinx gallery transition PR](https://github.com/dipy/dipy/pull/1990/) they are reSructuredText files.

May be the Azure CI pipelines could be taught to build the documentation to test such changes?

**Comment by skoudoro** [comment]
The doc generation is already on Travis. There is no problem during the compilation but I do not know if it is visually correct. There are often many surprises and a visual check is always necessary.

I would love to see people starting to have this habit to generate the documentation on their own laptop to check if everything is ok visually since the generation takes only 30sec (at the opposite of DIPY 😄)

**Comment by skoudoro** [comment]
As you can see [here on Travis](https://travis-ci.org/fury-gl/fury/jobs/645835305#L1665), documentation generation is failing. Can you have a look to see why @jhlegarreta? 
Thanks

**Comment by jhlegarreta** [comment]
Thanks @skoudoro ! Following your note I tried to build the docs locally and got the same error, so I will close this PR and open a new one transitioning to reSructuredText.

**Comment by jhlegarreta** [comment]
PR #144 proposes the transition to reStructuredText.

**Pull request closed without merging**
