### PR TITLE
changed text position

### PR DESCRIPTION
**Pull request by PaulNicolasHunter**
changed text position to - "above the slider" in the horizontal slider

### CODE REVIEW

**Comment by skoudoro** [comment]
Currently, your change is static and we want it to be more accessible to the user.

**Comment by PaulNicolasHunter** [comment]
@skoudoro Noted, I'll work to make it user accessible.
Now, I think PR #165 is merged to base too, so I'll take that into consideration as well.

**Comment by PaulNicolasHunter** [comment]
Hi, @skoudoro I've made a new PR (#188), however, most of the tests are failing, can you please guide me on how to rectify them.

**Comment by skoudoro** [comment]
closing in favor of #189

**Pull request closed without merging**
