### PR TITLE
Added blogpost week 2

### PR DESCRIPTION
**Pull request by tvcastillod**
Hello, here is the blog post for week 2.

week-2

### CODE REVIEW

**Review by JoaoDell — CHANGES_REQUESTED** [review]
Hey @tvcastillod nice blogpost and it built sucessfully here, just check my comments below and this will be ready to be merged 👍

**Review by ganimtron-10 — COMMENTED** [review]
Hey @tvcastillod ,
Short and Nice Blog.
LGTM.

**Review by skoudoro — COMMENTED** [review]
Thanks all for the review.  After fixing what is pointed by Joao, It will be ready to be merged

**Review by skoudoro — APPROVED** [review]
thank you for the update, merging

**Pull request merged**
