### PR TITLE
Namanb009 Remove mulitple actors

### PR DESCRIPTION
**Pull request by namanb009**
Type: Feature 
Improve: Ease of access

Users will now be able to remove more than one actor from scene with a single line of code.

### CODE REVIEW

**Comment by skoudoro** [comment]
Hi @namanb009,

Thank for this. Can you rebase or create a new branch? This is a nice update but 12 commits for this change is a lot....

Otherwise, do not forget to add a test for this new feature.

**Comment by namanb009** [comment]
Hello, @skoudoro I am sorry it got a little messy. It's because I updated my master branch and reverted a few merges.

**Comment by namanb009** [comment]
@skoudoro Please checkout PR#215 Sorry for the mess

**Comment by skoudoro** [comment]
superseded by #215. Closing

**Pull request closed without merging**
