### PR TITLE
Fixed the rotation matrix in repeat_primitive.

### PR DESCRIPTION
**Pull request by m-agour**
Fixed the issue of the rotation matrix that I mentioned in issue #554. 
What I did was assume all primitives have a normal vector pointing in X-axis (1, 0, 0), then the matrix to align this normal vector of the primitives to the direction vector specified.
I tested the matrix on my arrow using **repeat_primitive** and **repeat_source** and got a match.
```
import numpy as np
from fury import window, actor

scene = window.Scene()

centers = np.zeros([3, 3])
dirs = np.identity(3)
colors = np.identity(3)
scales = np.array([2.1, 2.6, 2.5])

rpactor = actor.arrow(centers, dirs, colors=colors, scales=1.5)
rsactor = actor.arrow(centers, dirs, colors=colors, repeat_primitive=False)

cen2 = np.random.rand(5, 3)
dir2 = np.random.rand(5, 3)
cols2 = np.random.rand(5, 3)

rpactor2 = actor.arrow(cen2, dir2, colors=cols2, scales=1.5)
rsactor2 = actor.arrow(cen2, dir2, colors=cols2, repeat_primitive=False)

scene.add(rpactor)
scene.add(rpactor2)
scene.add(rsactor)
scene.add(rsactor2)

window.show(scene, size=(600, 600), reset_camera=False, title='Comparing')
```

image

As shown in the figure above, they align perfectly now.

### CODE REVIEW

**Review by skoudoro — COMMENTED** [review]
Hi @m-agour,

Apologize for the late answer. Good catch and thank you for this!

Can you update the tests in `fury/test/test_primitive.py`

Thank you

**Comment by m-agour** [comment]
Hello @skoudoro ,
Ok, I will update the tests in test_primitive.py

**Comment by skoudoro** [comment]
Before going further in your test, can you merge #551 in your PR (or rebase).

Both are linked. thank you @m-agour

**Comment by m-agour** [comment]
Hello @skoudoro .
Sorry for the late reply, I just finished my midterms and will get right into it.

**Pull request merged**
