### PR TITLE
Add Physics simulation examples.

### PR DESCRIPTION
**Pull request by Nibba2018**
The following simulations are added:
* [X] Brick wall
* [x] Ball Collision
* [x] Chain Simulation
* [x] Wrecking Ball Simulation

close #236

### CODE REVIEW

**Comment by Nibba2018** [comment]
Hello @skoudoro , check the `viz_brick_wall.py` file and let me know if its okay.

**Comment by skoudoro** [comment]
Thank you @Nibba2018, Overall, it looks good. I need to run those examples to make sure we have no surprise. After that, I will go ahead and merge your PR. Thanks!

**Comment by skoudoro** [comment]
Hi @Nibba2018, Can you reduce the duration of all your simulations. They are a bit too long for the doc generation. Apart from that, everything is good. Thanks

**Comment by Nibba2018** [comment]
Hello @skoudoro , I have reduced the simulation duration.

**Comment by skoudoro** [comment]
Thank you for the update. Looking forward for your blog post. Merging

**Pull request merged**
